name: barber_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+13
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  get: ^4.3.8
  get_storage: ^2.0.3
  hive: ^2.0.4
  http: ^0.13.1 
  badges: ^2.0.2
  intl: ^0.17.0
  permission_handler: ^8.3.0
  google_fonts: ^2.0.0
  photo_view: ^0.11.1
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.4.0
  cloud_firestore: ^1.0.5
  firebase_storage: ^8.0.5
  firebase_messaging: ^10.0.3
  awesome_notifications: any
  
  url_launcher: ^6.0.3
  maps_launcher: ^2.0.0
  file_picker: ^3.0.1
  file_picker_cross: ^4.3.2
  path_provider: ^2.0.1
  uuid: ^3.0.4
  table_calendar: ^3.0.0
  geolocator: ^8.0.1
  clipboard: ^0.1.3
  disk_space: ^0.2.1
  firedart: ^0.9.0+1
  flutter_rating_bar: ^4.0.0
  flutter_colorpicker: ^1.0.3
  flutter_image_compress: ^1.0.0
  image_compression: ^1.0.3
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  flutter_credit_card: ^3.0.1
  
dependency_overrides:
  disk_space:
  platform:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audio/
    - assets/document/
    - assets/image/
    - assets/gif/
    - assets/video/
    - assets/font/